// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3xHIRU-g6uyS3KX5nuxXNdiKb5AFaQM',
    appId: '1:748902285994:web:0c3040c5d587bd17f286d3',
    messagingSenderId: '748902285994',
    projectId: 'filimlistapp999',
    authDomain: 'filimlistapp999.firebaseapp.com',
    storageBucket: 'filimlistapp999.firebasestorage.app',
    measurementId: 'G-RZ123F99DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMwv5JvBc29LbomixyPxW6buVW039f5w',
    appId: '1:748902285994:android:d427ce6320910f33f286d3',
    messagingSenderId: '748902285994',
    projectId: 'filimlistapp999',
    storageBucket: 'filimlistapp999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhqn1pVJEJDoDaDx2NalWUfFKPvwk7zoY',
    appId: '1:748902285994:ios:952b7bceab6b030ff286d3',
    messagingSenderId: '748902285994',
    projectId: 'filimlistapp999',
    storageBucket: 'filimlistapp999.firebasestorage.app',
    iosBundleId: 'com.example.filimListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhqn1pVJEJDoDaDx2NalWUfFKPvwk7zoY',
    appId: '1:748902285994:ios:952b7bceab6b030ff286d3',
    messagingSenderId: '748902285994',
    projectId: 'filimlistapp999',
    storageBucket: 'filimlistapp999.firebasestorage.app',
    iosBundleId: 'com.example.filimListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl3xHIRU-g6uyS3KX5nuxXNdiKb5AFaQM',
    appId: '1:748902285994:web:50b9d21e4739f716f286d3',
    messagingSenderId: '748902285994',
    projectId: 'filimlistapp999',
    authDomain: 'filimlistapp999.firebaseapp.com',
    storageBucket: 'filimlistapp999.firebasestorage.app',
    measurementId: 'G-83S734D5XH',
  );
}
